[package]
name = "eyeball-im"
version = "0.2.6"
edition = "2021"
description = "Observable collections based on the `im` crate."
license.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[package.metadata.docs.rs]
all-features = true

[dependencies]
futures-core.workspace = true
imbl = {path = "../../imbl"}
tokio.workspace = true
tokio-util.workspace = true
tracing = { workspace = true, optional = true }

[dev-dependencies]
stream_assert.workspace = true

[lints]
workspace = true
