[package]
name = "eyeball-im"
version = "0.2.3"
edition = "2021"
license = "MPL-2.0"
description = "Observable collections based on the `im` crate."
repository = "https://github.com/jplatte/eyeball"

[package.metadata.docs.rs]
all-features = true

[dependencies]
futures-core.workspace = true
imbl = "2.0.0"
tokio.workspace = true
tokio-util.workspace = true
tracing = { workspace = true, optional = true }

[dev-dependencies]
futures-util.workspace = true
stream_assert.workspace = true

[lints]
workspace = true
